//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoalPasswords.Language {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoalPasswords.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет аккаунта?.
        /// </summary>
        internal static string lDontHaveAccountString {
            get {
                return ResourceManager.GetString("lDontHaveAccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин:.
        /// </summary>
        internal static string lEmailString {
            get {
                return ResourceManager.GetString("lEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        internal static string lPasswordString {
            get {
                return ResourceManager.GetString("lPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        internal static string lSignInButton {
            get {
                return ResourceManager.GetString("lSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        internal static string lSignUpButton {
            get {
                return ResourceManager.GetString("lSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать!.
        /// </summary>
        internal static string lWelcomeString {
            get {
                return ResourceManager.GetString("lWelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все пароли.
        /// </summary>
        internal static string mAllPasswordsButton {
            get {
                return ResourceManager.GetString("mAllPasswordsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КАТЕГОРИИ.
        /// </summary>
        internal static string mCategoriesString {
            get {
                return ResourceManager.GetString("mCategoriesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кредитные карты.
        /// </summary>
        internal static string mCreditCardsButton {
            get {
                return ResourceManager.GetString("mCreditCardsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развлечения.
        /// </summary>
        internal static string mEntertainmentButton {
            get {
                return ResourceManager.GetString("mEntertainmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта.
        /// </summary>
        internal static string mMailButton {
            get {
                return ResourceManager.GetString("mMailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        internal static string mOtherButton {
            get {
                return ResourceManager.GetString("mOtherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акцентный цвет:.
        /// </summary>
        internal static string msAccentColorString {
            get {
                return ResourceManager.GetString("msAccentColorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически.
        /// </summary>
        internal static string msAutoCombo {
            get {
                return ResourceManager.GetString("msAutoCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема:.
        /// </summary>
        internal static string msColorThemeString {
            get {
                return ResourceManager.GetString("msColorThemeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмная.
        /// </summary>
        internal static string msDarkCombo {
            get {
                return ResourceManager.GetString("msDarkCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string msEnglishCombo {
            get {
                return ResourceManager.GetString("msEnglishCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупки.
        /// </summary>
        internal static string mShoppingButton {
            get {
                return ResourceManager.GetString("mShoppingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык:.
        /// </summary>
        internal static string msLanguageString {
            get {
                return ResourceManager.GetString("msLanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        internal static string msLightCombo {
            get {
                return ResourceManager.GetString("msLightCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string msLogOutButton {
            get {
                return ResourceManager.GetString("msLogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string msRussianCombo {
            get {
                return ResourceManager.GetString("msRussianCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас уже 27 записей. Спасибо!.
        /// </summary>
        internal static string msThanksString {
            get {
                return ResourceManager.GetString("msThanksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Украинский.
        /// </summary>
        internal static string msUkrainianCombo {
            get {
                return ResourceManager.GetString("msUkrainianCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа.
        /// </summary>
        internal static string mWorkButton {
            get {
                return ResourceManager.GetString("mWorkButton", resourceCulture);
            }
        }
    }
}
